name: Pre-Push Workflow

on:
  workflow_run:
    workflows: ["development"]
    types:
      - requested

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    name: Echo Hello World Job
    steps:
      - uses: actions/checkout@v4.1.1
      - run: echo Hello World!
