name: CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - run: |
                  uptime >> server_log.txt
                  ifconfig > server_ip_log.txt
                  pwd > server_pwd_log.txt
                  echo $(readlink -f ./server_pwd_log.txt) > server_cd_log.txt
                  git remote get-url origin >> server_git_log.txt
                  git config --global user.name "${{secrets.ID}}"
                  git config --global user.email "${{secrets.EMAIL}}"
                  git add .
                  git commit -m "updated github's server time"
                  git push
