name: Pre-Push Workflow

on:
  workflow_run:
    workflows: ["development"]
    types:
      - requested

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    name: Echo Hello World Job
    steps:
        echo Hello, world!
