name: Pre-Push Workflow

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4.1.1
