name: Checkout Repository

on:
  push:
    branches:
      - development  # 또는 원하는 브랜치

jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
